version: '3.4'
services:
  auth_server:
    build: ./auth_server
    depends_on:
      - auth_db
    env_file: .env
    ports:
      - "9000:9000"
  auth_db:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - authdata:/var/lib/postgresql/data
      - ./auth_server/db:/docker-entrypoint-initdb.d
  client:
    build: ./client
    depends_on:
      - auth_server
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      CLIENT_REDIRECT_URI: ${CLIENT_REDIRECT_URI}
      AUTH_SERVER_HOST: ${AUTH_SERVER_HOST}
    ports:
      - "5000:5000"
  resource_server:
    build: ./resource_server
    depends_on:
      - auth_server
    environment:
      RESOURCE_SERVER_NAME: ${RESOURCE_SERVER_NAME}
    ports:
      - "3000:3000"
volumes:
  authdata:
