version: '3.4'
services:
  auth_server:
    command: npm start
    volumes:
      - ./auth_server/src:/usr/auth_server/src
    environment:
      NODE_ENV: development
  auth_db:
    ports:
      - "5432:5432"
  client:
    command: npm start
    volumes:
      - ./client/src:/usr/client/src
    environment:
      NODE_ENV: development
  resource_server:
    command: npm start
    volumes:
      - ./resource_server/src:/usr/resource_server/src
    environment:
      NODE_ENV: development
