version: '3.4'
services:
  auth_server:
    command: npm start
    volumes:
      - ./auth_server/src:/usr/auth_server/src
    environment:
      NODE_ENV: development
  auth_db:
    ports:
      - "5432:5432"
