openapi: 3.0.2
info:
  title: Authorization server API specification
  version: '1.0'
paths:
  /authorize:
    get:
      description: Used to get the login form, genereted for a particular client specified in the query parameters
      parameters:
        - name: response_type
          in: query
          required: true
          description: Defines what response is expected by the client. The only available value is 'code'.
          schema:
            type: string
            example: 'code'
        - name: client_id
          in: query
          required: true
          description: The ID of a client issued after client registrations.
          schema:
            type: string
            example: 'sample-app'
        - name: redirect_uri
          in: query
          required: true
          description: The URL-encoded one of absolute uri predefined in the authorization server during client registration. Required for 'code' response_type.
          schema:
            type: string
            example: 'https%3A%2F%2Fsample.com%2F'
        - name: state
          in: query
          description: Random string generated by client to prevent CSRF attack.
          schema:
            type: string
            example: '6348d5df-02cf-4ddd-9586-407ea9890c0c'
        - name: code_challenge
          in: query
          required: true
          description: Code created via secret code transformation by the client
          schema:
            type: string
            example: 'E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM'
        - name: code_challenge_method
          in: query
          required: true
          description: A method used to make a transformation of secret code
          schema:
            type: string
            example: 'S256'
      responses:
        '200':
          description: Form successfully created
        '400':
          description: Invalid request
    post:
  /register:
    get:
    post:
  /token:
    post:
  /revoke:
    post:
  /.well-known/jwks.json:
    get:
